### ISSUE TITLE
Supporting CDK minishift deployment

### ISSUE THREAD

**Issue by eschabell** [redhatdemocentral/rhcs-rewards-demo#1]
When deploying on minishift CDK OCP getting errors using start.sh, can't write to /etc/passwd or /etc/groups.

**Comment by sabre1041** [comment]
@eschabell this is a combination of a carryover from the original non OpenShift runtime and the relaxing of strict permissions in the CDK to obey the user/group as defined in the Dockerfile. In `oc cluster up` and in production OpenShift environments, the id of the user running the container is randomized and the group id is root (0). In the CDK, it obeys the value within the Dockerfile. 

The solution would be to apply the changes as seen in the following link:

https://github.com/redhatdemocentral/rhcs-rewards-demo/compare/master...sabre1041:cdk-fix

I can submit a PR if you would like?

**Comment by eschabell** [comment]
@sabre1041, I can fix that, thanks, no need for the PR.
